### ISSUE TITLE
Failed build with proj-6.0.0

### ISSUE THREAD

**Issue by wenheping** [markov2/perl5-Geo-Proj4#3]
Build log say:

...
--- config ---
Running Mkbootstrap for Proj4 ()
--- Proj4.bs ---
chmod 644 "Proj4.bs"
--- blib/arch/auto/Geo/Proj4/Proj4.bs ---
"/usr/local/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Proj4.bs blib/arch/auto/Geo/Proj4/Proj4.bs 644
--- pm_to_blib ---
cp lib/Geo/Proj4.pm blib/lib/Geo/Proj4.pm
cp lib/Geo/Proj4.pod blib/lib/Geo/Proj4.pod
--- Proj4.c ---
mv Proj4.xsc Proj4.c
--- Proj4.o ---
cc -c  -I/usr/local/include -I.  -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing    -DVERSION=\"1.09\"  -DXS_VERSION=\"1.09\" -DPIC -fPIC "-I/usr/local/lib/perl5/5.28/mach/CORE"   Proj4.c
Proj4.xs:7:10: fatal error: 'projects.h' file not found
#include "projects.h"
         ^~~~~~~~~~~~
1 error generated.
*** [Proj4.o] Error code 1

**Comment by markov2** [comment]
Proj 5 and 6 are incompatible with release 4.  Geo::Proj4 currently only supports library version 4.  I am working on a solution (but that's quite hard to fix: the library does not implement backwards compatibility)

**Comment by wenheping** [comment]
Thank your reply.
But Geo-Proj4 could build with proj-5.1.0.
